tuple = (10,25+5j,"hello","learning","python",[10,20,30])
print("accessing the +ve nums: ")
print(tuple[0])
print(tuple[1])
print(tuple[2])
print(tuple[3])
print(tuple[4])
print(tuple[5])
print("accessing the -ve nums: ")
print(tuple[-1])
print(tuple[-2])
print(tuple[-3])
print(tuple[-4])
print(tuple[-5])
print(tuple[-6])